import mongoose from "mongoose";

const aboutSchema = new mongoose.Schema({
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
    },
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    pageTitle:{
        type:String,
        required:true
    },
    firstSection:{
        mainTitle:{
            type:String,
            required:true
        },
        subTitle:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            number:{
                type:String,
                required:true
            },
            value:{
                type:String,
                required:true
            }
        }]
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image1:{
            type:String,
            required:true
        },
        image2:{
            type:String,
            required:true
        },
        image1Alt:{
            type:String,
        },
        image2Alt:{
            type:String,
        }
    },
    historySection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            year:{
                type:String,
                required:true
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            }
        }]
    },
    purposeSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        }
    },
    coreValues:{
        title:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }],
    },
})

export default mongoose.models.About || mongoose.model("About", aboutSchema);