import mongoose from "mongoose";

const blastingSchema = new mongoose.Schema({
    metaTitle:{
        type:String
    },
    metaDescription:{
        type:String
    },
    pageTitle:{
        type:String
    },
    firstSection:{
        title:{
            type:String
        },
        description:{
            type:String
        },
        image:{
            type:String
        },
        imageAlt:{
            type:String
        }
    },
    secondSection:{
        title:{
            type:String
        },
        description:{
            type:String
        },
        image:{
            type:String
        },
        imageAlt:{
            type:String
        }
    },
    thirdSection:{
        title:{
            type:String
        },
        description:{
            type:String
        },
        image:{
            type:String
        },
        imageAlt:{
            type:String
        }
    },
    fourthSection:{
        title:{
            type:String
        },
        items:[{
            logoAlt:{
                type:String
            },
            title:{
                type:String
            },
            logo:{
                type:String
            },
            number:{
                type:String
            },
            value:{
                type:String
            },
            description:{
                type:String
            }
        }]
    },
    fifthSection:{
        title:{
            type:String
        },
        description:{
            type:String
        },
        items:[{
            logoAlt:{
                type:String
            },
            title:{
                type:String
            },
            description:{
                type:String
            },
            logo:{
                type:String
            }
        }]
    }
})

export default mongoose.models.Blasting || mongoose.model("Blasting", blastingSchema);