import mongoose from "mongoose";

const EngineeringSchema = new mongoose.Schema({
    metaTitle:{
        type:String
    },
    metaDescription:{
        type:String
    },
    pageTitle:{
        type:String,
        required:true
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        }
    },
    secondSection:{
        title:{
            type:String
        },
        description:{
            type:String
        },
        items:[
            {
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String,
                },
                title:{
                    type:String,
                    required:true
                },
                description:{
                    type:String,
                    required:true
                },
                logoAlt:{
                    type:String,
                },
                logo:{
                    type:String,
                    required:true
                }
            }
        ]
    },
    thirdSection:{
        title:{
            type:String
        },
        description:{
            type:String
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        },
        imageThumbnail:{
            type:String,
            required:true
        },
        imageAltThumbnail:{
            type:String,
        },
        threeDFile:{
            type:String,
            required:true
        },
        threeDFileAlt:{
            type:String,
        } 
    },
    fourthSection:{
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        },
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        }
    },
    fifthSection:{
        title:{
            type:String
        },
        items:[
            {
                title:{
                    type:String,
                    required:true
                },
                elements:[
                    {
                        logoAlt:{
                            type:String,
                        },
                        title:{
                            type:String,
                            required:true
                        },
                        description:{
                            type:String,
                            required:true
                        },
                        logo:{
                            type:String,
                            required:true
                        }
                    }
                ]
            }
        ]
    },
    sixthSection:{
        title:{
            type:String
        },
        description:{
            type:String
        },
        items:[
            {
                logoAlt:{
                    type:String,
                },
                title:{
                    type:String,
                    required:true
                },
                description:{
                    type:String,
                    required:true
                },
                logo:{
                    type:String,
                    required:true
                }
            }
        ]
    }
})

export default mongoose.models.Engineering || mongoose.model("Engineering", EngineeringSchema);