import mongoose from "mongoose";

const FabricationSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
    },
    metaDescription:{
        type:String,
    },
    pageTitle:{
        type:String,
        required:true
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            logo:{
                type:String,
                required:true
            }
        }]
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            style:{
                type:String,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            threeDFile:{
                type:String,
                required:true
            },
            threeDFileAlt:{
                type:String,
            },
            threeDFileThumbnail:{
                type:String,
                required:true
            },
            threeDFileAltThumbnail:{
                type:String,
            }
        }]
    },
    fifthSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            logo:{
                type:String,
                required:true
            },
            number:{
                type:String,
                required:true
            },
            value:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    sixthSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            logo:{
                type:String,
                required:true
            }
        }]
    }
    
});

export default mongoose.models.Fabrication || mongoose.model("Fabrication", FabricationSchema);