import mongoose from "mongoose";
import seoSchema from "./Seo";

const GlobalPresenceAfricaSchema = new mongoose.Schema({
    seo: {
        type: seoSchema,
    },
    firstSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        image:{
            type:String,
        },
        imageAlt:{
            type:String,
        },
    },
    secondSection:{
        title:{
            type:String,
        },
        items:[{
            value:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }]
    },
    thirdSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        subtitle:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }]
    },
    fourthSection:{
        title:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }]
    },
    fifthSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }]
    },
    sixthSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        items:[{
            logo:{
                type:String,
            },
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }]
    },
    seventhSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }]
    },
    eighthSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        items:[{
            logo:{
                type:String,
            },
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }],
        secondDescription:{
            type:String,
        },
    },
    ninthSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        subtitle:{
            type:String,
        },
        items:[{
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }],
    },
    tenthSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        items:[{
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }],
    },
    eleventhSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        cta:{
            text:{
                type:String,
            },
            url:{
                type:String,
            }
        },
        image:{
            type:String,
        },
        imageAlt:{
            type:String,
        }
    },
    twelfthSection:{
        title:{
            type:String,
        },
        items:[{
            title:{
                type:String,
            },
            description:{
                type:String,
            }
        }],
    },
});

export default mongoose.models.GlobalPresenceAfrica || mongoose.model("GlobalPresenceAfrica", GlobalPresenceAfricaSchema);