import mongoose from "mongoose";

const projectSchema = new mongoose.Schema({
    banner:{
        type:String,
    },
    bannerAlt:{
        type:String,
    },
    metaTitle:{
        type:String,
    },
    metaDescription:{
        type:String,
    },
    pageTitle:{
        type:String,
    },
    sector:{
        type:String
    },
    location:{
        type:String
    },
    categories:[{
        name:{
            type:String,
        },
        metaTitle:{
            type:String,
        },
        metaDescription:{
            type:String,
        },
        slug:{
            type:String,
        },
        projects:[{
            banner:{
                type:String,
            },
            bannerAlt:{
                type:String,
            },
            pageTitle:{
                type:String,
            },
            description:{
                type:String,
            },
            title:{
                type:String,
            },
            slug:{
                type:String,
            },
            sector:{
                type:String,
            },
            location:{
                type:String,
            },
            employer:{
                type:String,
            },
            contractor:{
                type:String,
            },
            consultant:{
                type:String,
            },
            scope:{
                type:String,
            },
            steelTonnage:{
                type:String,
            },
            thumbnail:{
                type:String,
            },
            thumbnailAlt:{
                type:String,
            },
            metaTitle:{
                type:String,
            },
            metaDescription:{
                type:String,
            },
            images:[String],
            index:{
                type:Number,
                default:0
            },
        }]
    }]
})

export default mongoose.models.Project || mongoose.model("Project", projectSchema);