import mongoose from "mongoose";
import seoSchema from "./Seo";

const projectSchema = new mongoose.Schema({
    banner:{
        type:String,
    },
    bannerAlt:{
        type:String,
    },
    seo: {
        type: seoSchema,
    },
    pageTitle:{
        type:String,
    },
    sector:{
        type:String
    },
    location:{
        type:String
    },
    categories:[{
        name:{
            type:String,
        },
        seo: {
            type: seoSchema,
        },
        slug:{
            type:String,
        },
        projects:[{
            banner:{
                type:String,
            },
            bannerAlt:{
                type:String,
            },
            pageTitle:{
                type:String,
            },
            description:{
                type:String,
            },
            title:{
                type:String,
            },
            slug:{
                type:String,
            },
            sector:{
                type:String,
            },
            location:{
                type:String,
            },
            employer:{
                type:String,
            },
            contractor:{
                type:String,
            },
            consultant:{
                type:String,
            },
            scope:{
                type:String,
            },
            steelTonnage:{
                type:String,
            },
            thumbnail:{
                type:String,
            },
            thumbnailAlt:{
                type:String,
            },
            metaTitle:{
                type:String,
            },
            metaDescription:{
                type:String,
            },
            ogTitle:{
                type:String
            },
            ogDescription:{
                type:String
            },
            ogType:{
                type:String
            },
            ogImage:{
                type:String
            },
            twitterTitle:{
                type:String
            },
            twitterDescription:{
                type:String
            },
            twitterImage:{
                type:String
            },
            schema:{
                type:String
            },
            images:[String],
            index:{
                type:Number,
                default:0
            },
        }]
    }]
})

export default mongoose.models.Project || mongoose.model("Project", projectSchema);