import mongoose from "mongoose";
import seoSchema from "./Seo";

const steelErectionSchema = new mongoose.Schema({
    seo: {
        type: seoSchema,
    },
    pageTitle:{
        type:String,
        required:true
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            }
        }]
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        }
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            }
        }]
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    }
})

export default mongoose.models.SteelErection || mongoose.model("SteelErection",steelErectionSchema)